### ISSUE TITLE
Use Jekyll for managing DatameetAMD website

### ISSUE THREAD

**Issue by gnatih** [DatameetAMD/DatameetAMD.github.io#2]
[Jekyll](https://jekyllrb.com) is a simple, blog-aware, static site generator. It allows better managing of static pages by making the code modular. 

I've created a separate repository as a demonstration for [OpenAhmedabad.org Website](https://github.com/gnatih/openahmedabad.org).

**Comment by gnatih** [comment]
Anything happening about the 'suggestion'??

**Comment by ndkcha** [comment]
Will lookup on how to merge the open-loo project with the website

**Comment by gnatih** [comment]
I guess this should be closed now that the website has been migrated.
